Jackett "Standalone" aka build using .NET framework
SynoCommunity/spksrc pull request #4207
Opened 2020-10-06 07:58 UTC by publicarray

_Motivation:_  https://github.com/SynoCommunity/spksrc/issues/3697#issuecomment-698116461
_Linked issues:_ #3697

CC @m4tt075

**Caveats:**
* Only `x64`, `ARM 8` and `ARM 7` are supported, so I've moved it to a new package: `jackett-dotnet`
* Currently the .NET framework keeps data in, so I used `docker run --name spksrc --rm -it -v /Users/seb/git/spksrc:/spksrc:delegated -v :/root/.dotnet synocommunity/spksrc:latest /bin/bash` to run docker

Build: https://github.com/publicarray/spksrc/releases/tag/jackett-dotnet-0.16.1583

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

2020-10-06 10:57 UTC, m4tt075 commented
@publicarray Thanks for copying me in. I've stopped using Synology NASs some time ago, and as such, am no longer maintaining this package. As such please feel free to put yourself or just SynoCommunity in as maintainer.

In any case, I remember very vividly that maintaining mono has been more than painful. As such, this PR and your efforts here to circumvent the mono dependency will clearly be beneficial and appreciated by the community!

2020-10-06 12:39 UTC, publicarray commented
Oh I am curious, Can I ask what you are using instead for storage?

Thanks for your kind words 🙏

2020-10-06 16:44 UTC, m4tt075 commented
I've built my own NAS. If you are interested in the background and you understand (some) German, you can find the whole story here: https://www.kodinerds.net/index.php/Thread/65922-Neues-NAS-Server/?pageNo=1.

2020-10-07 10:01 UTC, publicarray commented
@m4tt075 Thank you! That is very interesting. (Ich kann Deutsch sprechen 😄)

2020-11-26 20:21 UTC, ymartin59 requested changes
I recommend to replace original "jackett" (with Mono runtime) with new version compiled by dotNetCore and to confirm upgrade process allows user to keep application configuration and data.

2020-12-05 04:36 UTC, publicarray commented
@ymartin59 Done, I replaced the original jackett. Note that some older 32-bit architectures are not supported. I've also created generic makefiles for .net

2021-01-17 10:04 UTC, ymartin59 commented
@publicarray So it means package is no longer available for "evansport" whereas this architecture is still supported with DSM 7? It is quite annoying. What prevents i686 compilation to work with dotnet-core?

2021-01-17 11:13 UTC, hgy59 commented
> 
> 
> @publicarray So it means package is no longer available for "evansport" whereas this architecture is still supported with DSM 7? It is quite annoying. What prevents i686 compilation to work with dotnet-core?

There is no support for 32 bit linux with .NET (formerly named dotnet core). 32 bit is supported only on ARM (linux arm32) and windows (x86).
see [current versions](https://dotnet.microsoft.com/download/dotnet/5.0)

2021-02-07 13:34 UTC, ymartin59 requested changes
Looks good. But I would request effort to keep Jackett for archs not supported by dotnetcore, thanks to a conditional build with Mono. At least for archs still under support with DSM 7...

2021-02-07 13:34 UTC, ymartin59 commented on native/dotnet-sdk-5.0/Makefile
> +
Please discard these lines. Not relevant for "native" tool.

2021-02-07 13:34 UTC, ymartin59 commented on native/dotnet-sdk-5.0/Makefile
> +
Please discard these lines. Not relevant for "native" tool.

2021-02-07 13:34 UTC, ymartin59 commented on native/dotnet-sdk-3.1/Makefile
> +
Please discard these lines. Not relevant for "native" tool.

2021-02-07 13:34 UTC, ymartin59 commented on native/dotnet-sdk-3.1/Makefile
> +
Please discard these lines. Not relevant for "native" tool.

2021-02-08 07:38 UTC, publicarray commented on spk/jackett/Makefile
> +UNSUPPORTED_ARCHS = $(PPC_ARCHS) $(ARMv5_ARCHS) $(i686_ARCHS) $(ARMv7L_ARCHS)
I gave it a go, let me know what you think.

2021-02-08 07:41 UTC, publicarray commented on spk/jackett/Makefile
> +MAINTAINER = SynoCommunity
I rather not show up with my username in software that is most likely used for piracy.

2021-02-09 12:08 UTC, ymartin59 requested changes
Thanks for this effort. Looks good.
Does it really make sense to include dotnet-sdk-3.1 here? You may keep files aside for you/future applications, but I guess there is little chance an application remains on old sdk version?
Sorry but I still have some minor improvements. Then I will test this "branching" package as I have evansport.

2021-02-09 12:08 UTC, ymartin59 commented on spk/jackett/Makefile
> +CHANGELOG = "Compile using .NET Core"
I would manage ChangeLog conditionally according to target arch... either mono or dotnetcore

2021-02-09 12:08 UTC, ymartin59 commented on spk/jackett/Makefile
> +endif
Same statements. Please use a single "ifeq" condition with all of them, and include ChangeLog here

2021-02-09 12:48 UTC, publicarray commented
jellyfin is still on 3.1 (at least until 10.7 is released). But generally agree. 
3.1 is almost supported for another 2 years (2022-12-03). So I would keep it just in case for now.

2021-02-13 12:59 UTC, ymartin59 approved these changes

2021-02-14 09:01 UTC, merged

2021-02-21 09:10 UTC, Wuszek commented
After upgrading on DS218+, couldn't start package. Had to manually downgrade to last working version.

2021-02-21 10:57 UTC, publicarray commented
Thanks @Wuszek. Sigh. Why is it never simple... Are there any logs?

2021-02-21 11:46 UTC, Wuszek commented
Where do I look @publicarray ? Now I have installed Jackett from the previous release (and this mono version installed and started fine), but maybe logs are still somewhere over there

2021-02-21 12:05 UTC, publicarray commented
Thanks @Wuszek, Sorry do you have a log file at `cat /var/packages/jackett/target/var/jackett.log` ?

2021-02-21 12:23 UTC, Wuszek commented
@publicarray ok, so I just upgraded Jackett in Package Center and I get "Couldnt start up package" notification. This is jackett.log:

Sun Feb 21 13:21:56 CET 2021
Starting jackett command env HOME=/volume1/@appstore/jackett/var PATH=/volume1/@appstore/jackett/bin:/sbin:/bin:/usr/sbin:/usr/bin:/usr/syno/sbin:/usr/syno/bin:/usr/local/sbin:/usr/local/bin LD_LIBRARY_PATH=/volume1/@appstore/jackett/lib /volume1/@appstore/jackett/share/jackett --PIDFile /volume1/@appstore/jackett/var/jackett.pid 
/volume1/@appstore/jackett/share/jackett: /lib64/libstdc++.so.6: no version information available (required by /volume1/@appstore/jackett/share/jackett)
/volume1/@appstore/jackett/share/jackett: /lib64/libstdc++.so.6: no version information available (required by /volume1/@appstore/jackett/share/jackett)
/volume1/@appstore/jackett/share/jackett: /lib64/libstdc++.so.6: no version information available (required by /volume1/@appstore/jackett/share/jackett)
/volume1/@appstore/jackett/share/jackett: /lib64/libstdc++.so.6: no version information available (required by /volume1/@appstore/jackett/share/jackett)
/volume1/@appstore/jackett/share/jackett: /lib64/libstdc++.so.6: no version information available (required by /volume1/@appstore/jackett/share/jackett)
/volume1/@appstore/jackett/share/jackett: /lib64/libstdc++.so.6: no version information available (required by /volume1/@appstore/jackett/share/jackett)
/volume1/@appstore/jackett/share/jackett: relocation error: /volume1/@appstore/jackett/share/jackett: symbol _ZNSt25__codecvt_utf8_utf16_baseIDsED2Ev, version GLIBCXX_3.4.21 not defined in file libstdc++.so.6 with link time reference

2021-02-21 12:30 UTC, publicarray commented
Thanks that explains it clearly. The glibc is too old. The x64 I'm testing on has a slightly newer version.

2021-02-21 12:38 UTC, Wuszek commented
Is there a command to check which version I am using? I tried
`strings /usr/lib/libstdc++.so.6 | grep LIBCXX`

but there is no strings command

2021-02-21 17:02 UTC, Wuszek commented
@publicarray ping me pls when there would be fix for this, Im willing to test this

2021-02-21 21:48 UTC, publicarray commented
Thanks @Wuszek what is the output of `ls -l /usr/lib/libstdc++.so.6` ?

```
ls -l /lib64/libc.so.6
lrwxrwxrwx 1 root root 20 Dec 14 17:36 /lib64/libc.so.6 -> libc-2.20-2014.11
ls -l /lib64/libstdc++.so.6
lrwxrwxrwx 1 root root 19 Dec 14 17:36 /usr/lib/libstdc++.so.6 -> libstdc++.so.6.0.20
```

As a workaround you can copy the lib from a linux box:

```
$ scp /lib64/libstdc++.so.6 user@synology:/tmp/libstdc++.so.6
$ ssh user@synology
# sudo mv /tmp/libstdc++.so.6 /var/packages/jackett/target/lib/libstdc++.so.6
```

I've deactivated the .NET versions of the package for now

2021-02-21 22:43 UTC, Wuszek commented
@publicarray output:

```
root@SynologyNAS_WK:~# ls -l /usr/lib/libstdc++.so.6
lrwxrwxrwx 1 root root 19 May 26  2020 /usr/lib/libstdc++.so.6 -> libstdc++.so.6.0.20
```

2021-03-01 10:09 UTC, ta264 commented
@Wuszek We're also very keen to finalize the switch away from mono for Radarr... Would you be up for joining the radarr discord and trying out a few ideas? https://radarr.video/discord