icecast: update dependencies and update for DSM7
SynoCommunity/spksrc pull request #4628
Opened 2021-05-11 18:15 UTC by hgy59

_Motivation:_  Icecast needs an update due to several security fixes
_Linked issues:_  depends on #4625 and #4626

### Checklist
- [x] Build rule `all-supported` completed successfully
- [x] Package upgrade completed successfully
- [x] New installation of package completed successfully

2021-05-14 22:02 UTC, ymartin59 requested changes
Good but I think it is required to support "var" relocation seamlessly for users

2021-05-14 22:02 UTC, ymartin59 commented on spk/icecast/Makefile
> +	sed -e 's|/var/packages/icecast/target/var|/var/packages/icecast/var|g' -i $(STAGING_DIR)/var/icecast.xml
So I guess it will be required to add DMS major version upgrade from 6 to 7 to move "var" content from upgrade backup archive to new location, to avoid user to have to do it manually or lose his configuration, am I right?

2021-05-15 11:00 UTC, hgy59 commented on spk/icecast/Makefile
> +	sed -e 's|/var/packages/icecast/target/var|/var/packages/icecast/var|g' -i $(STAGING_DIR)/var/icecast.xml
This is already implemented in the dsm7 installer (spksrc.service.installer.dsm7), but only for the var folder (not for etc, home or what ever is used by some packages)
```bash
preupgrade ()
{
    log_step "preupgrade"
    call_func "validate_preupgrade"

    # dsm6 -> dsm7
    # Migrate data to permanent storage
    if [ -d ${SYNOPKG_PKGDEST}/var -a ! "$(ls -A ${SYNOPKG_PKGVAR})" ]; then
        # only migrate when destination is empty
        $CP ${SYNOPKG_PKGDEST}/var/. ${SYNOPKG_PKGVAR} 2>&1 | install_log
    fi

    call_func "service_preupgrade" install_log
    call_func "service_save" install_log
    exit 0
}
```

And there is some WIP to use rsync for migration (#4579)

2021-11-12 21:11 UTC, ymartin59 approved these changes

2022-01-03 18:18 UTC, nmiller0113 commented
Does anyone know when this may get merged? I'd love to get this working on DSM 7

2022-01-03 22:04 UTC, hgy59 commented
@nmiller0113 you are welcome to test the current packages built by github build action (download packages.zip artifacts of the latests build action of this PR).
_i never streamed music with icecast, only tested the web UI_

2022-01-03 23:27 UTC, nmiller0113 commented
> 

Thanks @hgy59 but I'm not sure I know how to do that. I have just been running the package install from my Synology desktop previously.  Even if I download it, not sure of the proper way to instal it from the Synology CLI. If you have a place to point me to read about how to, I'd be more than happy to test it. Thanks!

2022-01-04 18:18 UTC, hgy59 commented
> Even if I download it, not sure of the proper way to instal it from the Synology CLI. If you have a place to point me to read about how to, I'd be more than happy to test it. Thanks!

You can manually install spk files in the DSM package center of your diskstation. You don't need any ssh terminal nor cli commands.

In the github build action page (reachabel via `Checks` tab above) you navigate to Artifacts to download packages. 
You can only download packages.zip containing all spk files successfully built by one github action.
As we mostly create packages for _generic archs_ you have to know the generic arch of your DS model to identify the correct spk file. You find the information on our wiki page [package architectures](https://github.com/SynoCommunity/spksrc/wiki/Synology-and-SynoCommunity-Package-Architectures). 
In the package center you find the `manual installallation` button right of the search field. Here you can choose a local spk file to install.

Such installations are compatible with installations from the synocommunity repo. i.e. you will get notified, when a newer version is available in the repo and you can update it.

Only in the case of errors with a package, you have to ssh into the diskstation to analyze log files etc.

2022-04-20 11:28 UTC, ymartin59 approved these changes

2022-05-29 11:02 UTC, misaka00251 commented
Just asking, when will this get merged? Is it not ready or still under review?

2022-05-29 22:50 UTC, hgy59 commented
> Just asking, when will this get merged? Is it not ready or still under review?

Finally I was able to test icecast. Except the large latency (as by design) a sample stream worked as expected.

2022-05-30 04:41 UTC, merged