Tvh update
SynoCommunity/spksrc pull request #4686
Opened 2021-06-19 00:48 UTC by th0ma7

_Motivation:_  Update DTV tables and to latest git hash
_Linked issues:_  #4680 and #4545

### Checklist
- [ ] Build rule `all-supported` completed successfully
- [ ] Package upgrade completed successfully
- [ ] New installation of package completed successfully

2021-06-20 09:51 UTC, th0ma7 commented
@hgy59 with the recent DSM7 wizard changes... I guess I should ensure to circumvent this somehow?

2021-06-22 22:08 UTC, th0ma7 commented
Ready for review.
Package build is looking quite good and been performing well for my own personal usage.
Currently available for beta testing through my github.
I intend to bump package version when ready for publishing (along with ffmpeg and others).

2021-06-23 17:07 UTC, hgy59 requested changes
two minor suggestions

2021-06-23 17:07 UTC, hgy59 commented on cross/dtv-scan-tables/Makefile
> +include ../../mk/spksrc.cross-cc.mk
you can omit `CONFIGURE_TARGET = nop` and `COMPILE_TARGET = nop` when you use 
```suggestion
include ../../mk/spksrc.install-resources.mk
```

2021-06-24 12:19 UTC, th0ma7 commented
> two minor suggestions

@hgy59 thnx, applied!

2021-06-24 12:26 UTC, merged