SickChill use a pypi based install - build testing only
SynoCommunity/spksrc pull request #5449
Opened 2022-10-13 15:09 UTC by BKSteve

## Description

SickChill update test with #5431 

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [x] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

2022-10-13 17:07 UTC, th0ma7 commented
Have you got it working?  If so, what was missing (seing the last build being succesful)

2022-10-13 17:13 UTC, BKSteve commented
Waiting for others not using x64 to report back. 
Everything else pretty clear with the changes

2022-10-14 07:52 UTC, BKSteve commented
@th0ma7 ultimately it was getting the requirements sorted out. (a couple of typos and bits)
Need to cross/cryptography (copied from your python 310 makefile)
Then a sickchill pyproject.toml clean up.

As of the last build using 20221013 and writing this have 1 positive working on a DS114 armv7 DSM6 
Everybody with x64 is of course working. I've tested on both DSM6 and DSM7 x64 devices.

2022-10-15 08:13 UTC, BKSteve commented
The `pip-cache` going into /var or /\@appdata is noted. 

Wondered why `cachedir=${SYNOPKG_PKGVAR}/pip-cache` in `spksrc.service.installer.functions` is `SYNOPKG_PKGVAR` rather than say `SYNOPKG_PKGDEST/share`

As this puts the cached pip items in the user variable location rather than package location. (\@appdata not \@appstore)

2022-10-15 08:19 UTC, BKSteve commented
We have x64, armv7 and evansport confirmed working on both DSM 6 & 7.

@th0ma7 grateful if you could run you eyes over this and then merge to master.

2022-10-15 12:06 UTC, th0ma7 requested changes
Overall LGTM besides building duplicate `cryptography` wheels (see comments below).

2022-10-15 12:06 UTC, th0ma7 commented on spk/sickchill/src/service-setup.sh
> +    # For cleaner update remove bin, env, share and lib folders for fresh install, leave user data /var & /@appdata
I'm surprised by this as normally the entire `target/*` directory (e.g. `${SYNOPKG_PKGDEST}) gets deleted at upgrade time.  Does this really have an effect?

2022-10-15 12:06 UTC, th0ma7 commented on spk/sickchill/src/requirements-crossenv.txt
> +cryptography==38.0.1
Now I noticed this, so you're building both `py310-py310` and a `py36-abi3` wheels.  Therefore you end-up having two versions of the same wheel in the `work-<arch>-<ver>/wheelhouse/cryptography*.whl`.  Only one is needed.

Can you check which version was used on your tested installations as you should only be keeping one or the other.

2022-10-15 12:10 UTC, th0ma7 commented
> The `pip-cache` going into /var or /@appdata is noted.
> 
> Wondered why `cachedir=${SYNOPKG_PKGVAR}/pip-cache` in `spksrc.service.installer.functions` is `SYNOPKG_PKGVAR` rather than say `SYNOPKG_PKGDEST/share`
> 
> As this puts the cached pip items in the user variable location rather than package location. (@appdata not @appstore)

Previously everything was under the `target` directory (e.g. `SYNOPKG_PKGDEST`).  Starting with DSM7 you can uninstall a package without uninstalling the user-files and upgrade also now avoid impacting user-files as well (on DSM6 we needed to temporarily copy them elsewhere).

For all theses reasons, having the `pip-cache` located there makes it relevant as otherwise it would get deleted at every package upgrade, thus removing the interest of caching in the first place.  By being under the `var` directory, on older much slower targets, it fasten the upgrade process significantly.

2022-10-18 02:16 UTC, th0ma7 commented
Sorry for the very limited cycles this week (and on my cellphone).  Try setting up `SERVICE_USER = AUTO` in `Makefile`.

2022-10-18 02:58 UTC, BKSteve commented
Will try with `auto` changed to `AUTO` in makefile as already there with lowercase.

Is there any way to modify the `service-setup.sh` file and build a new package without going through the full build process with `packages` ?
So after the build and everything in `work` folder just tweak service-setup.sh and build new SPK.

2022-10-18 08:34 UTC, th0ma7 commented
Awesome, great work!  And yes you can simply use `make spkclean` or `wheelclean` to invoke rebuilds.

Leave me a few day before doing a review + merge + publishing.  Ping me by EOW if you don't hear back from me.

2022-10-18 21:33 UTC, th0ma7 approved these changes

2022-10-18 21:33 UTC, merged

2022-10-18 21:35 UTC, th0ma7 commented
awesome work, thnx for your contribution!
now merged and building + publishing in progress

2022-10-19 03:19 UTC, th0ma7 commented on spk/sickchill/Makefile
> +SERVICE_USER = AUTO
I'm now not so sure.  @hgy59 may know more about it.  In the meantime tomorrow i'll disable the packages on-line until we figure it out.

2022-10-19 07:04 UTC, BKSteve commented
Sorry think I messed this up. #5458 
Did this so I can pull the built packages zip.

2022-10-19 16:06 UTC, hgy59 commented on spk/sickchill/Makefile
> +SERVICE_USER = AUTO
IMHO `auto` is the only valid value for `SERVICE_USER`.

The install log entries (with `SERVICE_USER = auto`) are correct showing `... USER=sickchill GROUP=sc-download SHARE_PATH=` 
`$USER` is the base name and as variable for the user any install script must use `$EFF_USER` (is either `sc-sickchill` for DSM >= 6 or `svc-sickchill` for DSM < 6.

2022-10-19 16:32 UTC, miigotu commented on spk/sickchill/Makefile
> +SERVICE_USER = AUTO
As I suspected. The question is, how to correct ownership when keeping data between upgrades from dsm6=>dsm7?

Also, is there a proper location to store our database and configuration, or at least backups, outside the spk install directory?

Thanks.