git: udpate to v2.39.0 and add git-lfs (#5528)
SynoCommunity/spksrc pull request #5532
Opened 2022-12-20 23:00 UTC by hgy59

## Description

Fixes # 

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [x] Package update

2022-12-22 21:41 UTC, hgy59 commented
@th0ma7 please have a look for the solution to add additional features to cross/curl (for tvheadend).

2022-12-29 21:51 UTC, ymartin59 requested changes
Please move out the two intruder files. Except these, LGTM

2022-12-29 21:51 UTC, ymartin59 commented on cross/tvheadend/Makefile
> +DEPENDS += cross/libwebsockets
File not related to git, please move changeset to another PR

2022-12-29 21:51 UTC, ymartin59 commented on diyspk/curl/Makefile
> +SPK_NAME = curl
File not related to git, please move changeset to another PR

2022-12-29 22:51 UTC, hgy59 commented
> @th0ma7 please have a look for the solution to add additional features to cross/curl (for tvheadend).

Theupdate of curl/tvheadend is moved to PR #5543

2023-01-19 20:54 UTC, merged