Framework: Add publish validation check
SynoCommunity/spksrc pull request #5701
Opened 2023-04-20 13:27 UTC by mreid-tt

## Description

This PR was motivated by inconsistencies observed in the package publish process. It was noted that when the package is sent to the repository, there was no checking to confirm that the package was successfully received and added. This PR seeks to add this functionality.

Fixes # 

## Checklist

- [ ] Build rule `all-supported` completed successfully
- [ ] New installation of package completed successfully
- [ ] Package upgrade completed successfully (Manually install the package again)
- [ ] Package [functionality was tested](https://github.com/SynoCommunity/spksrc/wiki/Package-Update-Policy#tests-checks)
- [ ] Any needed [documentation](https://github.com/SynoCommunity/spksrc/wiki/Create-documentation) is updated/created

### Type of change

- [ ] Bug fix
- [ ] New Package
- [ ] Package update
- [ ] Includes small framework changes
- [ ] This change requires a documentation update (e.g. Wiki)

2023-04-23 13:44 UTC, th0ma7 requested changes
This looks good.  Could you look into ensuring the logs gets duplicated so it goes through the `publish-<arch>-<version>.log` as well such as what's being made at line 634:
```
... | tee --append build-$*.log >(grep -e '^http' -e '^{"package":' -e '^{"message":' >> publish-$*.log) ; \
```

Also, something I found missing is adding to `.gitignore` the following:
```
spk/*/publish*
```

2023-04-23 16:20 UTC, mreid-tt commented
@th0ma7, thanks for the review. Let me know if I've implemented your recommendations correctly.

2023-04-23 19:36 UTC, th0ma7 reviewed
LGTM

2023-04-23 19:36 UTC, th0ma7 approved these changes

2023-04-26 01:32 UTC, merged

2023-04-26 11:00 UTC, mreid-tt commented
@th0ma7, it's working! For packages I am publishing I get the following in the logs for successful responses:

```
  Package published successfully
  {"package": "prowlarr", "version": "20230426-6", "firmware": "6.1-15047", "architectures": ["evansport"]}
```

And for failed actions we get the following:

```
ERROR: Failed to publish package - HTTP response code 500
```

More importantly, the job exits with a failed status as follows:

```
Error: ERRORS:
23.04.26 09:24:44 - prowlarr: (evansport-7.1) FAILED
```

So we are very clear that these need to re-run and no jobs give a false positive for publishing.

2023-04-26 11:11 UTC, th0ma7 commented
Excellent!